<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Kelly Cao Data Analysis Portfolio - CDC-Data Exercise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Kelly Cao Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html" rel="" target="">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html" rel="" target="">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html" rel="" target="">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html" rel="" target="">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html" rel="" target="">
 <span class="dropdown-text">CDC-Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../fitting-exercise/fitting-exercise.html" rel="" target="">
 <span class="dropdown-text">Fitting Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../ml-models-exercise/ml-models-exercise.html" rel="" target="">
 <span class="dropdown-text">Machine Learning Model Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kcao1199/kellycao-MADA-portfolio" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CDC-Data Exercise</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>The following <a href="https://data.cdc.gov/NCHS/NCHS-Leading-Causes-of-Death-United-States/bi63-dtpu/about_data">data sets</a> was provided from the National Center for Health Statistics (NCHS) and was found on the CDC’s data website. The data summarizes information regarding leading causes of death for United States’ residents. The data was collected from death certificates in the 50 states and the District of Columbia from 1999-2017. It can be found in the following link:</p>
<ul>
<li><a href="https://data.cdc.gov/NCHS/NCHS-Leading-Causes-of-Death-United-States/bi63-dtpu/about_data">CDC Link</a></li>
</ul>
<section id="loading-data-set" class="level2">
<h2 class="anchored" data-anchor-id="loading-data-set">Loading Data Set</h2>
<div class="cell" style="background-color: lightgray;">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Required packages are loaded. These packages are for data processing.cleaning, visualizing, file referencing, creating tables, etc.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)   </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)   </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)    </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)   </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)  </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The data set has 6 variables and 10,686 observations. The variables include:</p>
<ul>
<li>Year</li>
<li>X113.Cause.Name (the Cause of Death with regards to <a href="https://www-doh.state.nj.us/doh-shad/query/NCHS113.html">NCHS 113 Select Causes of Death</a>)</li>
<li>Cause.Name (cause of death)</li>
<li>State</li>
<li>Deaths (number of deaths)</li>
<li>Age.adjusted.Death.Rate (Age-adjusted death rates per 100,000 population)</li>
</ul>
<div class="cell" style="background-color: lightgray;">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Reading in the .csv file into the object "cause_of_death"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>cdc_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"cdcdata-exercise"</span>, <span class="st">"Leading_Cause_of_Death.csv"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Summarizing </span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Year      X113.Cause.Name     Cause.Name           State          
 Min.   :1999   Length:10868       Length:10868       Length:10868      
 1st Qu.:2003   Class :character   Class :character   Class :character  
 Median :2008   Mode  :character   Mode  :character   Mode  :character  
 Mean   :2008                                                           
 3rd Qu.:2013                                                           
 Max.   :2017                                                           
     Deaths        Age.adjusted.Death.Rate
 Min.   :     21   Min.   :   2.6         
 1st Qu.:    612   1st Qu.:  19.2         
 Median :   1718   Median :  35.9         
 Mean   :  15460   Mean   : 127.6         
 3rd Qu.:   5756   3rd Qu.: 151.7         
 Max.   :2813503   Max.   :1087.3         </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cdc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10868 obs. of  6 variables:
 $ Year                   : int  2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 ...
 $ X113.Cause.Name        : chr  "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" ...
 $ Cause.Name             : chr  "Unintentional injuries" "Unintentional injuries" "Unintentional injuries" "Unintentional injuries" ...
 $ State                  : chr  "United States" "Alabama" "Alaska" "Arizona" ...
 $ Deaths                 : int  169936 2703 436 4184 1625 13840 3037 2078 608 427 ...
 $ Age.adjusted.Death.Rate: num  49.4 53.8 63.7 56.2 51.8 33.2 53.6 53.2 61.9 61 ...</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Age-adjusted death rates (per 100,000 population) are based the 2000 US standard population. The death rates for post 2010, uses the census required US standard population of 2010. When reviewing age-adjusted death rates, look below for more context:</p>
<p><u> <strong>Missouri Department of Health’s Definition:</strong> </u> (Missouri Department of Health &amp; Senior Services)</p>
<p>Age-Adjusted Death Rates (AADR) = <span class="math inline">\(\sum (ASDR \times \text{standard proportion})\)</span></p>
<p>Age-specific Death Rate (ASDR) = <span class="math inline">\(\frac{\text{deaths in age group}}{\text{estimated population of that age group}} \times 100,000\)</span>.</p>
<p><u> <strong>CDC’s Definition</strong> (CDC, 2022) </u></p>
<p><span class="math inline">\(\sum_{i=1}^{n} {r_i \times (p_i / P)}{}\)</span></p>
<p><span class="math inline">\(r_i = \text{rate in age group } i \text{ in the population of interest}\)</span></p>
<p><span class="math inline">\(p_i = \text{standard population in age group } i\)</span></p>
<p><span class="math inline">\(P = \sum_{i=1}^{n} \frac{p_i}{n}\)</span></p>
<p><span class="math inline">\(n = \text{total number of age groups over the age range of the age-adjusted rate}\)</span></p>
</div>
</div>
</section>
<section id="processing-and-cleaning-data-set" class="level2">
<h2 class="anchored" data-anchor-id="processing-and-cleaning-data-set">Processing and Cleaning Data Set</h2>
<p>I first renamed the column names in the data set, as they were not too clear in what they represented. I then removed one of of the column in the data set, as it became redundant and was comparable to another column. I chose the <code>Cause of Death</code> column over <code>Cause of Death_X113</code> column for simplicity sake, as that column also included other information not relevant and required cleaning. I then removed the rows from certain columns that did not bring any legitimate or viable information. I then used the <code>na.omit()</code> function to omit any rows that had any non-answered columns. As the number of observations did not change, I could deduce that there were none. I then adjusted the years column into year ranges and made them continuous for greater ease of use.</p>
<div class="cell" style="background-color: lightgray;">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Renaming the columns for clarity and using str() to determine if the change of name took.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cdc_data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Year"</span>, <span class="st">"Cause of Death_X113"</span>, <span class="st">"Cause of Death"</span>, <span class="st">"State"</span>, <span class="st">"Number of Deaths"</span>, <span class="st">"Age-Adjusted Death Rates"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cdc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10868 obs. of  6 variables:
 $ Year                    : int  2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 ...
 $ Cause of Death_X113     : chr  "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" ...
 $ Cause of Death          : chr  "Unintentional injuries" "Unintentional injuries" "Unintentional injuries" "Unintentional injuries" ...
 $ State                   : chr  "United States" "Alabama" "Alaska" "Arizona" ...
 $ Number of Deaths        : int  169936 2703 436 4184 1625 13840 3037 2078 608 427 ...
 $ Age-Adjusted Death Rates: num  49.4 53.8 63.7 56.2 51.8 33.2 53.6 53.2 61.9 61 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I removed the column `Cause of Death_X113` for simplicity sake, as it seemed redundant with the next column, which did not contain the cause of death codes. </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>cdc_data <span class="ot">&lt;-</span> cdc_data <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="st">`</span><span class="at">Cause of Death_X113</span><span class="st">`</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#I removed any rows with columns in the "State" column that answered "United States"</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>cdc_data <span class="ot">&lt;-</span> cdc_data <span class="sc">%&gt;%</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(State <span class="sc">!=</span> <span class="st">"United States"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co">#I removed any rows with columns in the "Cause of Death" column that answered "All Causes"</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>cdc_data <span class="ot">&lt;-</span> cdc_data <span class="sc">%&gt;%</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Cause of Death</span><span class="st">`</span><span class="sc">!=</span> <span class="st">"All causes"</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co">#I used the na.omit() function to ensure the data set did not have any data that was NA</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>cdc_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(cdc_data)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="co">#With the column Years, I arranged them into ranges, so I may have an easier time performing any analysis later on with more distinct categorical levels</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>breaks <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1999</span>, <span class="dv">2000</span>, <span class="dv">2003</span>, <span class="dv">2006</span>, <span class="dv">2009</span>, <span class="dv">2012</span>, <span class="dv">2015</span>, <span class="dv">2018</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"1999"</span>, <span class="st">"2000-2002"</span>, <span class="st">"2003-2005"</span>, <span class="st">"2006-2008"</span>, <span class="st">"2009-2011"</span>, <span class="st">"2012-2014"</span>, <span class="st">"2015-2017"</span>)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>cdc_data<span class="sc">$</span>Year_Range <span class="ot">&lt;-</span> <span class="fu">cut</span>(cdc_data<span class="sc">$</span>Year, <span class="at">breaks =</span> breaks, <span class="at">labels =</span> labels, <span class="at">include.lowest =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Creating the distinct ranges for the years were performed with ChatGPT 3.5. After cleaning the data, I was left with 9690 observation of 6 variables.</p>
</section>
<section id="descriptive-analysis-of-processed-data" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-analysis-of-processed-data">Descriptive Analysis of Processed Data</h2>
<p><u> Categorical Variables </u></p>
<p>Using the <code>summary(cdc_data$Year==)</code> command, I was able to discern that each year collected 572 observations. I double checked this by entering the same command in the console to ensure that each year had the same number of observations. I used the table() function to determine the number of categories in the Cause of Death column. From this I was able to determine that there was 9 possible answer choices for that column, and each cause of death had the same number of observation in this data set. I then decided to calculate the proportion each of the answers make for each categorical variable.</p>
<div class="cell" style="background-color: lightgray;">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Determining the summary of each year category</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_data<span class="sc">$</span>Year<span class="sc">==</span><span class="dv">1999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Mode   FALSE    TRUE 
logical    9180     510 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabulating the categorical variables to discern the frequency of the output. I applied to result of the table() function an object for each categorical variable. I then used pop.table() function to determine the proportion of each answer and printed it. I discovered the prop.table() function for ChatGPT 3.5.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>cause_of_death_table <span class="ot">&lt;-</span> <span class="fu">table</span>(cdc_data<span class="sc">$</span><span class="st">`</span><span class="at">Cause of Death</span><span class="st">`</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>cause_of_death_percentages <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(cause_of_death_table)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cause_of_death_percentages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Alzheimer's disease                  Cancer                    CLRD 
                     10                      10                      10 
               Diabetes           Heart disease Influenza and pneumonia 
                     10                      10                      10 
         Kidney disease                  Stroke                 Suicide 
                     10                      10                      10 
 Unintentional injuries 
                     10 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>state_table <span class="ot">&lt;-</span> <span class="fu">table</span>(cdc_data<span class="sc">$</span>State)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>state_percentages <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(state_table)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(state_percentages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
             Alabama               Alaska              Arizona 
            1.960784             1.960784             1.960784 
            Arkansas           California             Colorado 
            1.960784             1.960784             1.960784 
         Connecticut             Delaware District of Columbia 
            1.960784             1.960784             1.960784 
             Florida              Georgia               Hawaii 
            1.960784             1.960784             1.960784 
               Idaho             Illinois              Indiana 
            1.960784             1.960784             1.960784 
                Iowa               Kansas             Kentucky 
            1.960784             1.960784             1.960784 
           Louisiana                Maine             Maryland 
            1.960784             1.960784             1.960784 
       Massachusetts             Michigan            Minnesota 
            1.960784             1.960784             1.960784 
         Mississippi             Missouri              Montana 
            1.960784             1.960784             1.960784 
            Nebraska               Nevada        New Hampshire 
            1.960784             1.960784             1.960784 
          New Jersey           New Mexico             New York 
            1.960784             1.960784             1.960784 
      North Carolina         North Dakota                 Ohio 
            1.960784             1.960784             1.960784 
            Oklahoma               Oregon         Pennsylvania 
            1.960784             1.960784             1.960784 
        Rhode Island       South Carolina         South Dakota 
            1.960784             1.960784             1.960784 
           Tennessee                Texas                 Utah 
            1.960784             1.960784             1.960784 
             Vermont             Virginia           Washington 
            1.960784             1.960784             1.960784 
       West Virginia            Wisconsin              Wyoming 
            1.960784             1.960784             1.960784 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>year_table <span class="ot">&lt;-</span> <span class="fu">table</span>(cdc_data<span class="sc">$</span>Year)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>year_percentages <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(year_table)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(year_percentages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1999     2000     2001     2002     2003     2004     2005     2006 
5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 
    2007     2008     2009     2010     2011     2012     2013     2014 
5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 
    2015     2016     2017 
5.263158 5.263158 5.263158 </code></pre>
</div>
</div>
<p>From the answers above, I was able to determine that all of the categorical variables in this data set have the same percentage for each category in a variable.</p>
<hr>
<p><u> Continuous Variables </u></p>
<p>I then plotted the continuous variables: <code>Number of Deaths</code> and <code>Age-Adjusted Death Rates</code> to determine its distribution. The summary statistics of the variables were shown in the object <code>summary_table</code>. I then printed the table with the <code>knitr</code> package and the <code>kableEXTRA</code> package. The latter package was discovered when attempting to adjust the visual of the table when using ChatGPT 3.5.</p>
<div class="cell" style="background-color: lightgray;">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plotted the continuous variables</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cdc_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Number of Deaths</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1000</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">'Histogram of Number of Deaths'</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Number of Deaths'</span>) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Frequency'</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cdc_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Age-Adjusted Death Rates</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">fill =</span> <span class="st">"lightgreen"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">'Histogram of Age-Adjusted Death Rates'</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Age-Adjusted Death Rates'</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Frequency'</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I then created the objects to store the two continuous variables</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>summary_variable1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(cdc_data<span class="sc">$</span><span class="st">`</span><span class="at">Number of Deaths</span><span class="st">`</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>summary_variable2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(cdc_data<span class="sc">$</span><span class="st">`</span><span class="at">Age-Adjusted Death Rates</span><span class="st">`</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co">#I then created a table with the summary statistics of both variables</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">c</span>(<span class="st">"Number of Deaths"</span>, <span class="st">"Age-Adjusted Death Rates"</span>),</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Min =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"Min."</span>], summary_variable2[<span class="st">"Min."</span>]),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q1 =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"1st Qu."</span>], summary_variable2[<span class="st">"1st Qu."</span>]),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Median =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"Median"</span>], summary_variable2[<span class="st">"Median"</span>]),</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mean =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"Mean"</span>], summary_variable2[<span class="st">"Mean"</span>]),</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">StDev =</span> <span class="fu">c</span>(<span class="fu">sd</span>(summary_variable1), <span class="fu">sd</span>(summary_variable2)),</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q3 =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"3rd Qu."</span>], summary_variable2[<span class="st">"3rd Qu."</span>]),</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">Max =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"Max."</span>], summary_variable2[<span class="st">"Max."</span>])</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="co">#Printing the table with the summary statistics of the two variables</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(summary_table, </span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Summary statistics of Number of Deaths and Age-Adjusted Death Rates"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary statistics of Number of Deaths and Age-Adjusted Death Rates</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">StDev</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Number of Deaths</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">536.0</td>
<td style="text-align: right;">1413.00</td>
<td style="text-align: right;">3744.12621</td>
<td style="text-align: right;">28670.502</td>
<td style="text-align: right;">3257.75</td>
<td style="text-align: right;">71930.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age-Adjusted Death Rates</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: right;">18.3</td>
<td style="text-align: right;">31.45</td>
<td style="text-align: right;">60.47208</td>
<td style="text-align: right;">129.967</td>
<td style="text-align: right;">55.00</td>
<td style="text-align: right;">347.4</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="conclusion-and-discussion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-and-discussion">Conclusion and Discussion</h2>
<p>The data set that was provided by the CDC was fairly clean and did not require much cleaning or processing. When attempting to analyze the individual variables, it became apparent that the categorical variables had a more uniform distribution, with an equal number of observations per category. The continuous variables when plotted showed a more exponential distribution, with many of it’s observations being in the lower end of its range.</p>
<p>When reviewing the statistics of the continuous variables, it become apparent how great the variation is in each variable, The column “Number of Deaths” has a mean of 3744.12621 and a high standard deviation of 28670.502. The column “Age-Adjusted Death Rates” has a mean of 60.47208 and a standard deviation of 129.967. With such a high standard deviation, it is suggested that both variables have a greater spread of data</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li><p>Missouri Department of Health and Senior Services. (n.d.). Age-adjusted rates. Retrieved from https://health.mo.gov/data/mica/CDP_MICA/AARate.html</p></li>
<li><p>Centers for Disease Control and Prevention. (August 12, 2022). Age adjustment. Retrieved from https://www.cdc.gov/nchs/hus/sources-definitions/age-adjustment.htm</p></li>
</ul>
<p><strong>This section is contributed by Malika Dhakhwa</strong></p>
<p>The original data includes 10 causes of death. There are 19 years of data for each of the causes of death for 51 states from 1999 to 2017. I simulated the categorical variables, Year, State and Cause of Death using these parameters. Combining these, I created a data frame ‘synthetic_data’ which has 9690 observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Generating a column of 19 years starting from 1999 to 2017. ChatGPT helped me to find out the expand.grid function.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>Year <span class="ot">&lt;-</span> <span class="dv">1999</span><span class="sc">:</span><span class="dv">2017</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Generating 51 states assuming generic state names</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>states <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"State"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">51</span>) </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Generating Cause of Death</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>causes_of_death <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Alzheimer's disease"</span>, <span class="st">"Cancer"</span>, <span class="st">"CLRD"</span>, <span class="st">"Diabetes"</span>, <span class="st">"Heart disease"</span>, </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Influenza and pneumonia"</span>, <span class="st">"Kidney disease"</span>, <span class="st">"Stroke"</span>, <span class="st">"Suicide"</span>, <span class="st">"Unintentional injuries"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>synthetic_data <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Year =</span> Year, <span class="at">State =</span> states, <span class="at">Cause_of_Death =</span> causes_of_death)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(synthetic_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   9690 obs. of  3 variables:
 $ Year          : int  1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 ...
 $ State         : Factor w/ 51 levels "State 1","State 2",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Cause_of_Death: Factor w/ 10 levels "Alzheimer's disease",..: 1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "out.attrs")=List of 2
  ..$ dim     : Named int [1:3] 19 51 10
  .. ..- attr(*, "names")= chr [1:3] "Year" "State" "Cause_of_Death"
  ..$ dimnames:List of 3
  .. ..$ Year          : chr [1:19] "Year=1999" "Year=2000" "Year=2001" "Year=2002" ...
  .. ..$ State         : chr [1:51] "State=State 1" "State=State 2" "State=State 3" "State=State 4" ...
  .. ..$ Cause_of_Death: chr [1:10] "Cause_of_Death=Alzheimer's disease" "Cause_of_Death=Cancer" "Cause_of_Death=CLRD" "Cause_of_Death=Diabetes" ...</code></pre>
</div>
</div>
<p>I replaced the generic state with actual state names. ChatGPT helped me with the mapping.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mapping of placeholder names to actual state names</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>state_mapping <span class="ot">&lt;-</span> <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">"Alabama"</span>, <span class="st">"Alaska"</span>, <span class="st">"Arizona"</span>, <span class="st">"Arkansas"</span>, <span class="st">"California"</span>, <span class="st">"Colorado"</span>, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"Connecticut"</span>, <span class="st">"Delaware"</span>, <span class="st">"District of Columbia"</span>, <span class="st">"Florida"</span>, <span class="st">"Georgia"</span>, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"Hawaii"</span>, <span class="st">"Idaho"</span>, <span class="st">"Illinois"</span>, <span class="st">"Indiana"</span>, <span class="st">"Iowa"</span>, <span class="st">"Kansas"</span>, <span class="st">"Kentucky"</span>, </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"Louisiana"</span>, <span class="st">"Maine"</span>, <span class="st">"Maryland"</span>, <span class="st">"Massachusetts"</span>, <span class="st">"Michigan"</span>, <span class="st">"Minnesota"</span>, </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"Mississippi"</span>, <span class="st">"Missouri"</span>, <span class="st">"Montana"</span>, <span class="st">"Nebraska"</span>, <span class="st">"Nevada"</span>, <span class="st">"New Hampshire"</span>, </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"New Jersey"</span>, <span class="st">"New Mexico"</span>, <span class="st">"New York"</span>, <span class="st">"North Carolina"</span>, <span class="st">"North Dakota"</span>, </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"Ohio"</span>, <span class="st">"Oklahoma"</span>, <span class="st">"Oregon"</span>, <span class="st">"Pennsylvania"</span>, <span class="st">"Rhode Island"</span>, <span class="st">"South Carolina"</span>, </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"South Dakota"</span>, <span class="st">"Tennessee"</span>, <span class="st">"Texas"</span>, <span class="st">"Utah"</span>, <span class="st">"Vermont"</span>, <span class="st">"Virginia"</span>, </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"Washington"</span>, <span class="st">"West Virginia"</span>, <span class="st">"Wisconsin"</span>, <span class="st">"Wyoming"</span>), </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">paste</span>(<span class="st">"State"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">51</span>))</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Replacing the placeholder names in synthetic_data with actual state names using the mapping</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>synthetic_data<span class="sc">$</span>State <span class="ot">&lt;-</span> state_mapping[synthetic_data<span class="sc">$</span>State]</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking for accuracy </span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(synthetic_data<span class="sc">$</span>State)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Alabama" "Alabama" "Alabama" "Alabama" "Alabama" "Alabama"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(synthetic_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   9690 obs. of  3 variables:
 $ Year          : int  1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 ...
 $ State         : chr  "Alabama" "Alabama" "Alabama" "Alabama" ...
 $ Cause_of_Death: Factor w/ 10 levels "Alzheimer's disease",..: 1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "out.attrs")=List of 2
  ..$ dim     : Named int [1:3] 19 51 10
  .. ..- attr(*, "names")= chr [1:3] "Year" "State" "Cause_of_Death"
  ..$ dimnames:List of 3
  .. ..$ Year          : chr [1:19] "Year=1999" "Year=2000" "Year=2001" "Year=2002" ...
  .. ..$ State         : chr [1:51] "State=State 1" "State=State 2" "State=State 3" "State=State 4" ...
  .. ..$ Cause_of_Death: chr [1:10] "Cause_of_Death=Alzheimer's disease" "Cause_of_Death=Cancer" "Cause_of_Death=CLRD" "Cause_of_Death=Diabetes" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(synthetic_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Year         State                           Cause_of_Death
 Min.   :1999   Length:9690        Alzheimer's disease    : 969  
 1st Qu.:2003   Class :character   Cancer                 : 969  
 Median :2008   Mode  :character   CLRD                   : 969  
 Mean   :2008                      Diabetes               : 969  
 3rd Qu.:2013                      Heart disease          : 969  
 Max.   :2017                      Influenza and pneumonia: 969  
                                   (Other)                :3876  </code></pre>
</div>
</div>
<p>For simulating ‘No.&nbsp;of deaths’ and ‘Age-adjusted death rates’ in the synthetic data, I use the estimates of Year, state and Cause of death on the log of ‘No.&nbsp;of deaths’ and ‘Age-adjusted death rates’ obtained from the original data. To do this, I first fitted linear models using the original data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Renaming the columns of the original data temporarily for fitting the model to avoid the spaces and simplifying the syntax.</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cdc_data)[<span class="fu">names</span>(cdc_data) <span class="sc">==</span> <span class="st">"Number of Deaths"</span>] <span class="ot">&lt;-</span> <span class="st">"Number_of_Deaths"</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cdc_data)[<span class="fu">names</span>(cdc_data) <span class="sc">==</span> <span class="st">"Cause of Death"</span>] <span class="ot">&lt;-</span> <span class="st">"Cause_of_Death"</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cdc_data)[<span class="fu">names</span>(cdc_data) <span class="sc">==</span> <span class="st">"Age-Adjusted Death Rates"</span>] <span class="ot">&lt;-</span> <span class="st">"AADR"</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Fitting the linear model for log of 'Number of Deaths'</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>lm_log_Deaths <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Number_of_Deaths) <span class="sc">~</span> Year <span class="sc">+</span> <span class="fu">factor</span>(State) <span class="sc">+</span> <span class="fu">factor</span>(Cause_of_Death), <span class="at">data =</span> cdc_data)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>lm_log_Deaths</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Number_of_Deaths) ~ Year + factor(State) + factor(Cause_of_Death), 
    data = cdc_data)

Coefficients:
                                  (Intercept)  
                                   -15.499892  
                                         Year  
                                     0.011346  
                          factor(State)Alaska  
                                    -2.631253  
                         factor(State)Arizona  
                                     0.003643  
                        factor(State)Arkansas  
                                    -0.457314  
                      factor(State)California  
                                     1.620484  
                        factor(State)Colorado  
                                    -0.379651  
                     factor(State)Connecticut  
                                    -0.565903  
                        factor(State)Delaware  
                                    -1.891678  
            factor(State)District of Columbia  
                                    -2.497995  
                         factor(State)Florida  
                                     1.236063  
                         factor(State)Georgia  
                                     0.376874  
                          factor(State)Hawaii  
                                    -1.649134  
                           factor(State)Idaho  
                                    -1.416394  
                        factor(State)Illinois  
                                     0.747390  
                         factor(State)Indiana  
                                     0.202046  
                            factor(State)Iowa  
                                    -0.550949  
                          factor(State)Kansas  
                                    -0.609990  
                        factor(State)Kentucky  
                                    -0.085395  
                       factor(State)Louisiana  
                                    -0.109299  
                           factor(State)Maine  
                                    -1.293221  
                        factor(State)Maryland  
                                    -0.191319  
                   factor(State)Massachusetts  
                                     0.061227  
                        factor(State)Michigan  
                                     0.595212  
                       factor(State)Minnesota  
                                    -0.214052  
                     factor(State)Mississippi  
                                    -0.478931  
                        factor(State)Missouri  
                                     0.190847  
                         factor(State)Montana  
                                    -1.654428  
                        factor(State)Nebraska  
                                    -1.144469  
                          factor(State)Nevada  
                                    -0.923959  
                   factor(State)New Hampshire  
                                    -1.527223  
                      factor(State)New Jersey  
                                     0.294695  
                      factor(State)New Mexico  
                                    -1.063613  
                        factor(State)New York  
                                     0.990054  
                  factor(State)North Carolina  
                                     0.521378  
                    factor(State)North Dakota  
                                    -2.019163  
                            factor(State)Ohio  
                                     0.818885  
                        factor(State)Oklahoma  
                                    -0.248317  
                          factor(State)Oregon  
                                    -0.415952  
                    factor(State)Pennsylvania  
                                     0.947478  
                    factor(State)Rhode Island  
                                    -1.675424  
                  factor(State)South Carolina  
                                    -0.152719  
                    factor(State)South Dakota  
                                    -1.840267  
                       factor(State)Tennessee  
                                     0.238119  
                           factor(State)Texas  
                                     1.249413  
                            factor(State)Utah  
                                    -1.146016  
                         factor(State)Vermont  
                                    -2.247963  
                        factor(State)Virginia  
                                     0.221954  
                      factor(State)Washington  
                                     0.016514  
                   factor(State)West Virginia  
                                    -0.781371  
                       factor(State)Wisconsin  
                                     0.017620  
                         factor(State)Wyoming  
                                    -2.325557  
                 factor(Cause_of_Death)Cancer  
                                     2.017137  
                   factor(Cause_of_Death)CLRD  
                                     0.600338  
               factor(Cause_of_Death)Diabetes  
                                    -0.034050  
          factor(Cause_of_Death)Heart disease  
                                     2.101562  
factor(Cause_of_Death)Influenza and pneumonia  
                                    -0.304687  
         factor(Cause_of_Death)Kidney disease  
                                    -0.588815  
                 factor(Cause_of_Death)Stroke  
                                     0.625631  
                factor(Cause_of_Death)Suicide  
                                    -0.666365  
 factor(Cause_of_Death)Unintentional injuries  
                                     0.535392  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Fitting the linear model for 'Age-Adjusted Death Rates'</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>lm_AADR <span class="ot">&lt;-</span> <span class="fu">lm</span>(AADR <span class="sc">~</span> Year <span class="sc">+</span> <span class="fu">factor</span>(State) <span class="sc">+</span> <span class="fu">factor</span>(Cause_of_Death), <span class="at">data =</span> cdc_data)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>lm_AADR</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = AADR ~ Year + factor(State) + factor(Cause_of_Death), 
    data = cdc_data)

Coefficients:
                                  (Intercept)  
                                    1882.7197  
                                         Year  
                                      -0.9192  
                          factor(State)Alaska  
                                     -14.7132  
                         factor(State)Arizona  
                                     -16.9621  
                        factor(State)Arkansas  
                                      -1.0926  
                      factor(State)California  
                                     -17.7700  
                        factor(State)Colorado  
                                     -19.4279  
                     factor(State)Connecticut  
                                     -20.4679  
                        factor(State)Delaware  
                                     -11.9584  
            factor(State)District of Columbia  
                                      -9.8437  
                         factor(State)Florida  
                                     -17.4747  
                         factor(State)Georgia  
                                      -8.0547  
                          factor(State)Hawaii  
                                     -25.7053  
                           factor(State)Idaho  
                                     -14.9195  
                        factor(State)Illinois  
                                     -12.5142  
                         factor(State)Indiana  
                                      -6.7821  
                            factor(State)Iowa  
                                     -14.4537  
                          factor(State)Kansas  
                                     -12.7321  
                        factor(State)Kentucky  
                                       0.9379  
                       factor(State)Louisiana  
                                      -0.8732  
                           factor(State)Maine  
                                     -12.4874  
                        factor(State)Maryland  
                                     -15.1758  
                   factor(State)Massachusetts  
                                     -19.2879  
                        factor(State)Michigan  
                                      -8.9100  
                       factor(State)Minnesota  
                                     -22.2426  
                     factor(State)Mississippi  
                                       4.2426  
                        factor(State)Missouri  
                                      -5.8016  
                         factor(State)Montana  
                                     -13.5532  
                        factor(State)Nebraska  
                                     -16.5868  
                          factor(State)Nevada  
                                      -8.8389  
                   factor(State)New Hampshire  
                                     -15.5737  
                      factor(State)New Jersey  
                                     -16.7442  
                      factor(State)New Mexico  
                                     -14.9495  
                        factor(State)New York  
                                     -17.0289  
                  factor(State)North Carolina  
                                      -9.3574  
                    factor(State)North Dakota  
                                     -16.4347  
                            factor(State)Ohio  
                                      -7.3579  
                        factor(State)Oklahoma  
                                       0.9063  
                          factor(State)Oregon  
                                     -16.0874  
                    factor(State)Pennsylvania  
                                     -11.1116  
                    factor(State)Rhode Island  
                                     -15.7116  
                  factor(State)South Carolina  
                                      -6.5289  
                    factor(State)South Dakota  
                                     -13.9963  
                       factor(State)Tennessee  
                                      -1.3111  
                           factor(State)Texas  
                                     -11.8305  
                            factor(State)Utah  
                                     -20.7479  
                         factor(State)Vermont  
                                     -15.5589  
                        factor(State)Virginia  
                                     -13.6826  
                      factor(State)Washington  
                                     -15.7000  
                   factor(State)West Virginia  
                                       0.8032  
                       factor(State)Wisconsin  
                                     -14.9347  
                         factor(State)Wyoming  
                                     -11.5605  
                 factor(Cause_of_Death)Cancer  
                                     153.5837  
                   factor(Cause_of_Death)CLRD  
                                      19.6052  
               factor(Cause_of_Death)Diabetes  
                                      -1.6291  
          factor(Cause_of_Death)Heart disease  
                                     172.9024  
factor(Cause_of_Death)Influenza and pneumonia  
                                      -6.8265  
         factor(Cause_of_Death)Kidney disease  
                                     -10.9622  
                 factor(Cause_of_Death)Stroke  
                                      20.8678  
                factor(Cause_of_Death)Suicide  
                                     -11.5956  
 factor(Cause_of_Death)Unintentional injuries  
                                      18.4553  </code></pre>
</div>
</div>
<p>I used the above coefficients to calculate the predicted log of ‘Number of Deaths’ for each observation in the synthetic data and then exponentiate predicted values to get the original Number of Deaths. I followed similar steps for the Age-adjusted Death Rate. ChatGPT helped me with finding the ‘predict’ function to do this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the predicted values of log of deaths for the synthetic data</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>predicted_log_deaths <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_log_Deaths, <span class="at">newdata =</span> synthetic_data, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Converting log of 'Number of Deaths' back to the original scale and adding the column to the synthetic data</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>synthetic_data<span class="sc">$</span>Number_of_Deaths <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">exp</span>(predicted_log_deaths))</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the predicted values of Age-adjusted death rates in the column</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>predicted_AADR <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_AADR, <span class="at">newdata =</span> synthetic_data, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding the predicted Age-adjusted death rates to the synthetic data</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>synthetic_data<span class="sc">$</span>Age_adjusted_Death_Rate <span class="ot">&lt;-</span> <span class="fu">round</span>(predicted_AADR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Following my collaborator, I created a table of summary statistics to compare the distributions in the original data and the synthetic data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating the objects to store the two continuous variables</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>summary_variable1 <span class="ot">&lt;-</span> <span class="fu">summary</span>(synthetic_data<span class="sc">$</span>Number_of_Deaths)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>summary_variable2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(synthetic_data<span class="sc">$</span>Age_adjusted_Death_Rate)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co">#I then created a table with the summary statistics of both variables</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">c</span>(<span class="st">"Number_of_Deaths"</span>, <span class="st">"Age_adjusted_Death_Rate"</span>),</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Min =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"Min."</span>], summary_variable2[<span class="st">"Min."</span>]),</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q1 =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"1st Qu."</span>], summary_variable2[<span class="st">"1st Qu."</span>]),</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Median =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"Median"</span>], summary_variable2[<span class="st">"Median"</span>]),</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mean =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"Mean"</span>], summary_variable2[<span class="st">"Mean"</span>]),</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">StDev =</span> <span class="fu">c</span>(<span class="fu">sd</span>(summary_variable1), <span class="fu">sd</span>(summary_variable2)),</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q3 =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"3rd Qu."</span>], summary_variable2[<span class="st">"3rd Qu."</span>]),</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">Max =</span> <span class="fu">c</span>(summary_variable1[<span class="st">"Max."</span>], summary_variable2[<span class="st">"Max."</span>])</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Printing the table with the summary statistics of the two variables</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(summary_table, </span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Summary statistics of Synthetic Data"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary statistics of Synthetic Data</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">StDev</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Number_of_Deaths</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">538</td>
<td style="text-align: right;">1397</td>
<td style="text-align: right;">3646.45573</td>
<td style="text-align: right;">26508.08390</td>
<td style="text-align: right;">3349.75</td>
<td style="text-align: right;">66629</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age_adjusted_Death_Rate</td>
<td style="text-align: right;">-9</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">60.47245</td>
<td style="text-align: right;">81.77695</td>
<td style="text-align: right;">53.00</td>
<td style="text-align: right;">222</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The distribution of Number of Deaths and Age-adjusted Death Rates in the synthetic data are closely aligned with the original CDC data with the exception of the minimum values. The Age-adjusted Death Rates resulted a negative number (-9) for the minimum which is not meaningful. Upon a detailed review, I found that 0.59% (57) of the total observations have negative values for the Age-adjusted Death Rate, highlighting a need for correction to ensure the meaningfulness of these observations. Several strategies, including imputation and treating these as missing values, offer viable solutions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking counts of negative values</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>synthetic_data<span class="sc">$</span>Age_adjusted_Death_Rate[synthetic_data<span class="sc">$</span>Age_adjusted_Death_Rate <span class="sc">&lt;</span> <span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -1 -2 -3 -4 -1 -2 -1 -2 -3 -1 -2 -2 -3 -4 -5 -6 -7 -8 -1 -2 -1 -2 -3 -4 -5
[26] -1 -2 -3 -1 -1 -1 -2 -1 -2 -2 -3 -1 -2 -3 -4 -5 -6 -7 -8 -9 -1 -2 -1 -1 -2
[51] -3 -4 -5 -1 -2 -3 -4</code></pre>
</div>
</div>
<p>The histogram of the ‘Number of Deaths’ on the synthetic data resembles with that of the original data.The Age-adjusted Death Rates have lesser variability in the synthetic data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plotted the continuous variables</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(synthetic_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Number_of_Deaths</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1000</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">'Histogram of Number of Deaths  using Synthetic Data'</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Number of Deaths'</span>) <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Frequency'</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(synthetic_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Age_adjusted_Death_Rate</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">fill =</span> <span class="st">"lightgreen"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">'Histogram of Age-Adjusted Death Rates  from Synthetic Data'</span>) <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Age-Adjusted Death Rates'</span>) <span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Frequency'</span>) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Following my collaborator’s work, I summarized and tabulated the categorical variables to check frequency. As expected, the results are similar to the original data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Determining the summary of each year category</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(synthetic_data<span class="sc">$</span>Year<span class="sc">==</span><span class="dv">1999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Mode   FALSE    TRUE 
logical    9180     510 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Tabulating the categorical variables for frequency of the output following Kelly's method.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>cause_of_death_table <span class="ot">&lt;-</span> <span class="fu">table</span>(synthetic_data<span class="sc">$</span>Cause_of_Death )</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>cause_of_death_percentages <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(cause_of_death_table)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cause_of_death_percentages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Alzheimer's disease                  Cancer                    CLRD 
                     10                      10                      10 
               Diabetes           Heart disease Influenza and pneumonia 
                     10                      10                      10 
         Kidney disease                  Stroke                 Suicide 
                     10                      10                      10 
 Unintentional injuries 
                     10 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>state_table <span class="ot">&lt;-</span> <span class="fu">table</span>(synthetic_data<span class="sc">$</span>State)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>state_percentages <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(state_table)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(state_percentages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
             Alabama               Alaska              Arizona 
            1.960784             1.960784             1.960784 
            Arkansas           California             Colorado 
            1.960784             1.960784             1.960784 
         Connecticut             Delaware District of Columbia 
            1.960784             1.960784             1.960784 
             Florida              Georgia               Hawaii 
            1.960784             1.960784             1.960784 
               Idaho             Illinois              Indiana 
            1.960784             1.960784             1.960784 
                Iowa               Kansas             Kentucky 
            1.960784             1.960784             1.960784 
           Louisiana                Maine             Maryland 
            1.960784             1.960784             1.960784 
       Massachusetts             Michigan            Minnesota 
            1.960784             1.960784             1.960784 
         Mississippi             Missouri              Montana 
            1.960784             1.960784             1.960784 
            Nebraska               Nevada        New Hampshire 
            1.960784             1.960784             1.960784 
          New Jersey           New Mexico             New York 
            1.960784             1.960784             1.960784 
      North Carolina         North Dakota                 Ohio 
            1.960784             1.960784             1.960784 
            Oklahoma               Oregon         Pennsylvania 
            1.960784             1.960784             1.960784 
        Rhode Island       South Carolina         South Dakota 
            1.960784             1.960784             1.960784 
           Tennessee                Texas                 Utah 
            1.960784             1.960784             1.960784 
             Vermont             Virginia           Washington 
            1.960784             1.960784             1.960784 
       West Virginia            Wisconsin              Wyoming 
            1.960784             1.960784             1.960784 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>year_table <span class="ot">&lt;-</span> <span class="fu">table</span>(synthetic_data<span class="sc">$</span>Year)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>year_percentages <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(year_table)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(year_percentages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1999     2000     2001     2002     2003     2004     2005     2006 
5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 
    2007     2008     2009     2010     2011     2012     2013     2014 
5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 5.263158 
    2015     2016     2017 
5.263158 5.263158 5.263158 </code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>